export const TEST_IDS = {
  menuBar: "menu-bar",
  importButton: "import-button",
  importFileInput: "import-file-input",
  optionDialogOk: "option-dialog-ok",
  optionDialogCancel: "option-dialog-cancel",
  exportButton: "export-button",
  resetButton: "reset-button",
  userStyleAddButton: "user-style-add-button",
  userStyleSaveButton: "user-style-save-button",
  userStyleItem: "user-style-item",
  userStyleEditButton: "user-style-edit-button",
  userStyleRemoveButton: "user-style-remove-button",
  userStyleRemoveOkButton: "user-style-remove-ok-button",
  selectTrigger: (name: string) => `select-trigger-${name.replace(/\./g, "-")}`,
  selectItem: (name: string) => `select-item-${name.replace(/\./g, "-")}`,
}
