import { describe, it, expect } from "vitest"
import { OPEN_MODE } from "@/const"
import {
  ANALYTICS_EVENTS,
  getCommandCreateEvent,
  getHubAddEvent,
} from "@/services/analytics"

describe("getCommandCreateEvent", () => {
  it.each([
    [OPEN_MODE.POPUP, ANALYTICS_EVENTS.COMMAND_CREATE_SEARCH],
    [OPEN_MODE.WINDOW, ANALYTICS_EVENTS.COMMAND_CREATE_SEARCH],
    [OPEN_MODE.TAB, ANALYTICS_EVENTS.COMMAND_CREATE_SEARCH],
    [OPEN_MODE.BACKGROUND_TAB, ANALYTICS_EVENTS.COMMAND_CREATE_SEARCH],
    [OPEN_MODE.SIDE_PANEL, ANALYTICS_EVENTS.COMMAND_CREATE_SEARCH],
    [OPEN_MODE.AI_PROMPT, ANALYTICS_EVENTS.COMMAND_CREATE_AIPROMPT],
    [OPEN_MODE.API, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.PAGE_ACTION, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.LINK_POPUP, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.COPY, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.GET_TEXT_STYLES, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.OPTION, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
    [OPEN_MODE.ADD_PAGE_RULE, ANALYTICS_EVENTS.COMMAND_CREATE_OTHER],
  ] as const)("maps openMode %s to %s", (openMode, expected) => {
    expect(getCommandCreateEvent(openMode)).toBe(expected)
  })
})

describe("ANALYTICS_EVENTS onboarding events", () => {
  it("defines the event names used by the onboarding flow", () => {
    expect(ANALYTICS_EVENTS.ONBOARDING_START).toBe("onboarding_start")
    expect(ANALYTICS_EVENTS.ONBOARDING_SKIP).toBe("onboarding_skip")
    expect(ANALYTICS_EVENTS.ONBOARDING_FIRST_SELECTION).toBe(
      "onboarding_first_selection",
    )
    expect(ANALYTICS_EVENTS.ONBOARDING_COMMAND_EXECUTE).toBe(
      "onboarding_command_execute",
    )
    expect(ANALYTICS_EVENTS.ONBOARDING_FIRST_VALUE).toBe(
      "onboarding_first_value",
    )
    expect(ANALYTICS_EVENTS.ONBOARDING_COMPLETE).toBe("onboarding_complete")
  })
})

describe("getHubAddEvent", () => {
  it.each([
    [OPEN_MODE.POPUP, ANALYTICS_EVENTS.HUB_ADD_SEARCH],
    [OPEN_MODE.WINDOW, ANALYTICS_EVENTS.HUB_ADD_SEARCH],
    [OPEN_MODE.TAB, ANALYTICS_EVENTS.HUB_ADD_SEARCH],
    [OPEN_MODE.BACKGROUND_TAB, ANALYTICS_EVENTS.HUB_ADD_SEARCH],
    [OPEN_MODE.SIDE_PANEL, ANALYTICS_EVENTS.HUB_ADD_SEARCH],
    [OPEN_MODE.AI_PROMPT, ANALYTICS_EVENTS.HUB_ADD_AIPROMPT],
    [OPEN_MODE.API, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.PAGE_ACTION, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.LINK_POPUP, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.COPY, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.GET_TEXT_STYLES, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.OPTION, ANALYTICS_EVENTS.HUB_ADD_OTHER],
    [OPEN_MODE.ADD_PAGE_RULE, ANALYTICS_EVENTS.HUB_ADD_OTHER],
  ] as const)("maps openMode %s to %s", (openMode, expected) => {
    expect(getHubAddEvent(openMode)).toBe(expected)
  })
})
