#!/usr/bin/env vite-node
/**
 * Extracts search URLs from defaultSettings.ts and generates
 * e2e/generated-command-urls.ts for the URL status e2e test.
 *
 * Invoked automatically as part of "yarn build:e2e".
 */
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import {
  DefaultCommands,
  LOCALE_COMMANDS,
} from "@/services/option/defaultSettings"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT_PATH = path.resolve(__dirname, "../e2e/generated-command-urls.ts")
const IGNORE_PATH = path.resolve(__dirname, "e2e-ignore-urls.txt")

// Load ignored URLs from the ignore list
const ignoreUrls = new Set(
  fs
    .readFileSync(IGNORE_PATH, "utf-8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#")),
)

type Entry = { title: string; locale: string; searchUrl: string }

// Collect all entries: DefaultCommands as "en", then locale-specific ones
const allEntries: Entry[] = []

for (const cmd of DefaultCommands) {
  const c = cmd as Record<string, string>
  if (c.searchUrl) {
    allEntries.push({ title: c.title, locale: "en", searchUrl: c.searchUrl })
  }
}

for (const [locale, cmds] of Object.entries(LOCALE_COMMANDS)) {
  for (const cmd of cmds) {
    const c = cmd as Record<string, string>
    if (c.searchUrl) {
      allEntries.push({ title: c.title, locale, searchUrl: c.searchUrl })
    }
  }
}

// Deduplicate by searchUrl
const seen = new Set<string>()
const unique: Entry[] = []
for (const entry of allEntries) {
  if (!seen.has(entry.searchUrl) && !ignoreUrls.has(entry.searchUrl)) {
    seen.add(entry.searchUrl)
    unique.push(entry)
  }
}

// Write generated TypeScript file
const lines = unique
  .map(
    (e) =>
      `  { title: ${JSON.stringify(e.title)}, locale: ${JSON.stringify(e.locale)}, searchUrl: ${JSON.stringify(e.searchUrl)} },`,
  )
  .join("\n")

const output = `/**
 * Auto-generated by scripts/generate-e2e-urls.ts from defaultSettings.ts.
 * Do not edit manually. Run "yarn build:e2e" to regenerate.
 */

export type UrlEntry = { title: string; locale: string; searchUrl: string }

export const COMMAND_URLS: UrlEntry[] = [
${lines}
]
`

fs.writeFileSync(OUT_PATH, output, "utf-8")
console.log(`Generated ${OUT_PATH} with ${unique.length} URL entries.`)
