name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "packages/hub/**"
      - ".github/workflows/pages.yml"
      - ".github/workflows/update-data.yml"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build extension
        run: yarn build
        env:
          CI: true
