name: Release

on:
  push:
    tags:
      - "*"
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          CI: true
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
          VITE_API_SECRET: ${{ secrets.VITE_API_SECRET }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      - name: Create zip package
        run: |
          yarn zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
