name: Release

on:
  push:
    tags:
      - '*'
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: archive
        run: |
          zip -r chrome-ext.zip dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'chrome-ext.zip'
