name: Update Data
on:
  schedule:
    - cron: '0 3 * * *' # 毎日12:00 JST (3:00 UTC)に実行
  workflow_dispatch:

defaults:
  run:
    working-directory: ./pages

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'yarn'
      - name: Install dependencies
        run: yarn add @google-analytics/data
      - name: Fetch GA data
        env:
          GA_SERVICE_ACCOUNT_KEY: ${{ secrets.GA_SERVICE_ACCOUNT_KEY }}
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        run: node ./scripts/fetch-ga-data.js
      - name: Update Tag data
        run: node ./scripts/update-tags.mjs
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Update analytics data" || exit 0
          git push

  deploy-data:
    needs: update-data
    uses: ./.github/workflows/pages.yml
