/**
 * Auto-generated by scripts/generate-e2e-urls.ts from defaultSettings.ts.
 * Do not edit manually. Run "yarn build:e2e" to regenerate.
 */

export type UrlEntry = { title: string; locale: string; searchUrl: string }

export const COMMAND_URLS: UrlEntry[] = [
  { title: "Google", locale: "en", searchUrl: "https://google.com/search?q=%s" },
  { title: "Google Image", locale: "en", searchUrl: "https://google.com/search?q=%s&tbm=isch" },
  { title: "Youtube", locale: "en", searchUrl: "https://www.youtube.com/results?search_query=%s" },
  { title: "Netflix", locale: "en", searchUrl: "https://www.netflix.com/search?q=%s" },
  { title: "Pinterest", locale: "en", searchUrl: "https://www.pinterest.com/search/pins/?q=%s" },
  { title: "Drive", locale: "en", searchUrl: "https://drive.google.com/drive/search?q=%s" },
  { title: "Amazon", locale: "ja", searchUrl: "https://www.amazon.co.jp/s?k=%s" },
  { title: "Yahoo! Japan", locale: "ja", searchUrl: "https://search.yahoo.co.jp/search?p=%s" },
  { title: "en to ja", locale: "ja", searchUrl: "https://translate.google.co.jp/?hl=ja&sl=auto&text=%s&op=translate" },
  { title: "百度", locale: "zh", searchUrl: "https://www.baidu.com/s?wd=%s" },
  { title: "京东", locale: "zh", searchUrl: "https://search.jd.com/Search?keyword=%s" },
  { title: "哔哩哔哩", locale: "zh", searchUrl: "https://search.bilibili.com/all?keyword=%s" },
  { title: "네이버", locale: "ko", searchUrl: "https://search.naver.com/search.naver?query=%s" },
  { title: "Яндекс", locale: "ru", searchUrl: "https://yandex.ru/search/?text=%s" },
  { title: "ВКонтакте", locale: "ru", searchUrl: "https://vk.com/search?c%5Bq%5D=%s" },
  { title: "Amazon", locale: "es", searchUrl: "https://www.amazon.es/s?k=%s" },
  { title: "El Corte Inglés", locale: "es", searchUrl: "https://www.elcorteingles.es/search-nwx/?s=%s" },
  { title: "AliExpress", locale: "es", searchUrl: "https://es.aliexpress.com/w/wholesale-%s.html" },
  { title: "OLX", locale: "pt", searchUrl: "https://www.olx.pt/ads/?q=%s" },
  { title: "Tokopedia", locale: "id", searchUrl: "https://www.tokopedia.com/search?st=product&q=%s" },
  { title: "Shopee", locale: "id", searchUrl: "https://shopee.co.id/search?keyword=%s" },
  { title: "Shopee", locale: "ms", searchUrl: "https://shopee.com.my/search?keyword=%s" },
  { title: "Lazada", locale: "ms", searchUrl: "https://www.lazada.com.my/catalog/?q=%s" },
  { title: "Zalando.it", locale: "it", searchUrl: "https://www.zalando.it/catalogo/?q=%s" },
]
