/**
 * Auto-generated by scripts/generate-e2e-urls.mjs from defaultSettings.ts.
 * Do not edit manually. Run "yarn build:e2e" to regenerate.
 */

export type UrlEntry = { title: string; locale: string; searchUrl: string }

export const COMMAND_URLS: UrlEntry[] = [
  { title: "Google", locale: "en", searchUrl: "https://google.com/search?q=%s" },
  { title: "Google Image", locale: "en", searchUrl: "https://google.com/search?q=%s&tbm=isch" },
  { title: "Amazon", locale: "en", searchUrl: "https://www.amazon.com/s?k=%s" },
  { title: "Youtube", locale: "en", searchUrl: "https://www.youtube.com/results?search_query=%s" },
  { title: "Netflix", locale: "en", searchUrl: "https://www.netflix.com/search?q=%s" },
  { title: "Pinterest", locale: "en", searchUrl: "https://www.pinterest.com/search/pins/?q=%s" },
  { title: "Drive", locale: "en", searchUrl: "https://drive.google.com/drive/search?q=%s" },
  { title: "en to ja", locale: "en", searchUrl: "https://translate.google.co.jp/?hl=ja&sl=auto&text=%s&op=translate" },
  { title: "Amazon", locale: "ja", searchUrl: "https://www.amazon.co.jp/s?k=%s" },
  { title: "Yahoo! Japan", locale: "ja", searchUrl: "https://search.yahoo.co.jp/search?p=%s" },
  { title: "百度", locale: "zh", searchUrl: "https://www.baidu.com/s?wd=%s" },
  { title: "京东", locale: "zh", searchUrl: "https://search.jd.com/Search?keyword=%s" },
  { title: "哔哩哔哩", locale: "zh", searchUrl: "https://search.bilibili.com/all?keyword=%s" },
  { title: "知乎", locale: "zh", searchUrl: "https://www.zhihu.com/search?q=%s" },
  { title: "네이버", locale: "ko", searchUrl: "https://search.naver.com/search.naver?query=%s" },
  { title: "쿠팡", locale: "ko", searchUrl: "https://www.coupang.com/np/search?q=%s" },
  { title: "Яндекс", locale: "ru", searchUrl: "https://yandex.ru/search/?text=%s" },
  { title: "Ozon", locale: "ru", searchUrl: "https://www.ozon.ru/search/?text=%s" },
  { title: "Wildberries", locale: "ru", searchUrl: "https://www.wildberries.ru/catalog/0/search.aspx?search=%s" },
  { title: "ВКонтакте", locale: "ru", searchUrl: "https://vk.com/search?c%5Bq%5D=%s" },
  { title: "Amazon", locale: "de", searchUrl: "https://www.amazon.de/s?k=%s" },
  { title: "eBay", locale: "de", searchUrl: "https://www.ebay.de/sch/i.html?_nkw=%s" },
  { title: "Amazon", locale: "fr", searchUrl: "https://www.amazon.fr/s?k=%s" },
  { title: "leboncoin", locale: "fr", searchUrl: "https://www.leboncoin.fr/recherche?text=%s" },
  { title: "Amazon", locale: "es", searchUrl: "https://www.amazon.es/s?k=%s" },
  { title: "MercadoLibre", locale: "es", searchUrl: "https://listado.mercadolibre.com/%s" },
  { title: "Amazon", locale: "pt-BR", searchUrl: "https://www.amazon.com.br/s?k=%s" },
  { title: "Mercado Livre", locale: "pt-BR", searchUrl: "https://lista.mercadolivre.com.br/%s" },
  { title: "OLX", locale: "pt", searchUrl: "https://www.olx.pt/ads/?q=%s" },
  { title: "Amazon", locale: "hi", searchUrl: "https://www.amazon.in/s?k=%s" },
  { title: "Flipkart", locale: "hi", searchUrl: "https://www.flipkart.com/search?q=%s" },
  { title: "Tokopedia", locale: "id", searchUrl: "https://www.tokopedia.com/search?st=product&q=%s" },
  { title: "Shopee", locale: "id", searchUrl: "https://shopee.co.id/search?keyword=%s" },
  { title: "Shopee", locale: "ms", searchUrl: "https://shopee.com.my/search?keyword=%s" },
  { title: "Lazada", locale: "ms", searchUrl: "https://www.lazada.com.my/catalog/?q=%s" },
  { title: "Amazon", locale: "it", searchUrl: "https://www.amazon.it/s?k=%s" },
]
